language: node_js
sudo: true
addons:
  sauce_connect:
    username: 'leolin'
    access_key: '2d69d455-a8ff-45bd-8a93-5ba373ddf6a3'
node_js:
  - '4.4.2'
services: mongodb
cache:
  directories:
    - node_modules
before_install:
  - npm install
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run start
  - npm test
after_script:
  - npm run coverage